FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

ENV NODE_ENV=development \
    HOST=0.0.0.0 \
    PORT=3001 \
    NUXT_PORT=3001 \
    CHOKIDAR_USEPOLLING=true \
    NUXT_TELEMETRY_DISABLED=1 \
    NUXT_FORCE_COLOR=0

EXPOSE 3001

CMD ["npm", "run", "dev"]
