# Build stage
FROM node:20-alpine AS build
WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

# Production stage
FROM node:20-alpine
WORKDIR /app

COPY --from=build /app/.output ./

ENV HOST=0.0.0.0 \
    PORT=3001

EXPOSE 3001

CMD ["node", "server/index.mjs"]
